#!/bin/bash

R -e "install.packages('pak')"

# Imports
R -e "pak::pak('devtools')"
R -e "pak::pak('tidyverse')"
R -e "pak::pak('broom')"
R -e "pak::pak('caret')"
R -e "pak::pak('fastDummies')"
R -e "pak::pak('glue')"
R -e "pak::pak('gt')"
R -e "pak::pak('Hotelling')"
R -e "pak::pak('lifecycle')"
R -e "pak::pak('magrittr')"
R -e "pak::pak('mice')"
R -e "pak::pak('naniar')"
R -e "pak::pak('parallel')"
R -e "pak::pak('pROC')"
R -e "pak::pak('randomForest')"
R -e "pak::pak('survival')"
R -e "pak::pak('tableone')"
R -e "pak::pak('diffviewer')"
R -e "pak::pak('roxygen2@7.3.2')"

# Suggests
R -e "pak::pak('broom.helpers')"
R -e "pak::pak('cardx')"
R -e "pak::pak('gridExtra')"
R -e "pak::pak('gtsummary')"
R -e "pak::pak('here')"
R -e "pak::pak('knitr')"
R -e "pak::pak('reactR')"
R -e "pak::pak('reactable')"
R -e "pak::pak('rmarkdown')"
R -e "pak::pak('simsurv')"
R -e "pak::pak('smd')"
R -e "pak::pak('survminer')"
R -e "pak::pak('usethis')"
R -e "pak::pak('testthat')"
R -e "pak::pak('vdiffr')"
R -e "pak::pak('diffdf')"
